# Generated by Django 5.1.3 on 2024-11-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
